# -*- coding: utf-8 -*-
"""INTERFAZ V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxcZtuuPQY1sE5vsRa0KZblTp_6ozu8e
"""

##### CELDA 1: APERTURA DE LA INTERFAZ Y DEFINICIÓN DE TEMAS #######
# Objetivo:
# 1️⃣ Importar librerías necesarias.
# 2️⃣ Configurar la interfaz de Streamlit.
# 3️⃣ Inicializar variables de sesión del alumno.
# 4️⃣ Definir el diccionario TEMAS con niveles, descripción y ejercicios de referencia.

from backend import orquestador_manager, orquestador_pedagogico
import os
import streamlit as st

# -------------------------------------------------
# Cargar API Key desde Streamlit Secrets
# -------------------------------------------------
api_key = st.secrets.get("OPENAI_API_KEY")

if api_key:
    os.environ["OPENAI_API_KEY"] = api_key
else:
    st.error("No se encontró OPENAI_API_KEY en secrets.")



# -------------------------------------------------
# Configuración inicial de la página
# -------------------------------------------------
st.set_page_config(
    page_title="Agente Educativo de Algoritmos",
    layout="centered"
)

# -------------------------------------------------
# Inicialización del estado de sesión
# -------------------------------------------------
# Persistencia de datos del alumno durante la ejecución
if "sesion_iniciada" not in st.session_state:
    st.session_state.sesion_iniciada = False

if "alumno_id" not in st.session_state:
    st.session_state.alumno_id = None

if "actividad" not in st.session_state:
    st.session_state.actividad = None

if "color" not in st.session_state:
    st.session_state.color = None

# -------------------------------------------------
# Diccionario TEMAS con niveles, descripción y ejercicios de referencia
# -------------------------------------------------
# Este diccionario servirá de referencia para:
# - Determinar el nivel inicial y tema según historial
# - Mostrar descripción y ejercicios de cada tema
# - Ayudar al LLM a generar ejercicios adaptativos
TEMAS = {
    "Tema 1: Variables y tipos de datos": {
        "basico": {
            "descripcion": "Introducción a variables, tipos numéricos, texto y booleanos.",
            "ejercicios": [
                "Define una variable llamada 'edad' y asígnale tu edad.",
                "Crea una variable 'nombre' y almacena tu nombre.",
                "Dime el tipo de dato de 42, 'hola', True."
            ]
        },
        "intermedio": {
            "descripcion": "Operaciones con variables y conversión de tipos.",
            "ejercicios": [
                "Convierte la cadena '123' en número entero y súmale 7.",
                "Suma dos variables numéricas y almacena el resultado en una nueva variable.",
                "Concatena dos cadenas y muestra el resultado."
            ]
        },
        "avanzado": {
            "descripcion": "Expresiones complejas, múltiples variables y operadores.",
            "ejercicios": [
                "Crea tres variables con valores distintos y calcula la media.",
                "Define variables booleanas y usa operadores lógicos para combinarlas.",
                "Crea una variable que almacene un mensaje concatenando nombre y edad."
            ]
        }
    },
    "Tema 2: Programación secuencial": {
        "basico": {
            "descripcion": "Secuencia de instrucciones simples.",
            "ejercicios": [
                "Escribe un pseudocódigo que pida dos números y muestre su suma.",
                "Crea un algoritmo que multiplique tres números dados.",
                "Imprime tu nombre y tu edad en dos líneas."
            ]
        },
        "intermedio": {
            "descripcion": "Secuencias con operaciones intermedias y variables.",
            "ejercicios": [
                "Calcula el área de un rectángulo dado base y altura.",
                "Calcula el promedio de 5 calificaciones almacenadas en variables.",
                "Convierte una temperatura de Celsius a Fahrenheit."
            ]
        },
        "avanzado": {
            "descripcion": "Secuencias más largas con múltiples pasos y validaciones.",
            "ejercicios": [
                "Calcula el total de una compra con impuestos y descuento.",
                "Convierte metros a pies y luego calcula el doble de la medida.",
                "Dada la edad y la altura, imprime un mensaje personalizado según rangos."
            ]
        }
    },
    "Tema 3: Estructuras condicionales": {
        "basico": {
            "descripcion": "Condicional simple: if / else.",
            "ejercicios": [
                "Si la edad es mayor a 18, imprime 'Mayor de edad', si no 'Menor de edad'.",
                "Determina si un número dado es positivo o negativo.",
                "Verifica si un número es par o impar."
            ]
        },
        "intermedio": {
            "descripcion": "Condicional doble y anidado.",
            "ejercicios": [
                "Si la edad es mayor a 18 y tiene licencia, imprime 'Puede conducir'.",
                "Clasifica una nota en A, B, C, D según rangos.",
                "Verifica si un número está entre 10 y 20 o es mayor que 50."
            ]
        },
        "avanzado": {
            "descripcion": "Condicional múltiple y combinaciones lógicas complejas.",
            "ejercicios": [
                "Determina la categoría de un usuario según edad y puntaje.",
                "Evalúa múltiples condiciones combinando AND, OR, NOT.",
                "Construye una expresión lógica a partir de un enunciado complejo (ej: ingresos > 2000 y edad < 30)."
            ]
        }
    },
    "Tema 4: Estructuras repetitivas": {
        "basico": {
            "descripcion": "Bucles simples: for y while.",
            "ejercicios": [
                "Imprime los números del 1 al 10 usando un bucle.",
                "Suma los números del 1 al 20 usando while.",
                "Repite un mensaje 5 veces."
            ]
        },
        "intermedio": {
            "descripcion": "Bucles con condiciones y acumuladores.",
            "ejercicios": [
                "Suma todos los números pares entre 1 y 50.",
                "Calcula el factorial de un número usando un bucle.",
                "Imprime solo los números múltiplos de 3 hasta 30."
            ]
        },
        "avanzado": {
            "descripcion": "Bucles anidados y control de flujo avanzado.",
            "ejercicios": [
                "Imprime una tabla de multiplicar completa del 1 al 10.",
                "Genera un patrón de asteriscos en pirámide con bucles anidados.",
                "Itera listas de números y aplica condiciones complejas dentro del bucle."
            ]
        }
    }
}

##### CELDA 2: INICIO DE SESIÓN Y CONFIGURACIÓN VISUAL  #######

# Objetivo:
# 1. Permitir al alumno iniciar sesión indicando su ID, edad, actividad favorita y color de interfaz.
# 2. Mantener los datos del alumno en la sesión de Streamlit.
# 3. Asignar el primer tema y nivel desde el diccionario TEMAS.
# 4. Mostrar información básica del alumno después de iniciar sesión.

import streamlit as st

# -------------------------------------------------
# Pantalla de inicio / sesión pedagógica
# -------------------------------------------------
if not st.session_state.sesion_iniciada:

    st.title("🎓 Sistema Adaptativo de Algoritmos")
    st.write("Antes de comenzar, configura tu sesión de aprendizaje.")

    # Entrada del identificador del alumno
    alumno_id = st.number_input(
        "ID del alumno",
        min_value=1,
        step=1
    )

    # Entrada de la edad del alumno
    edad = st.number_input(
        "Edad del alumno",
        min_value=5,
        max_value=120,
        step=1
    )

    # Selección de actividad favorita (lista ampliada)
    actividad = st.selectbox(
        "Actividad favorita",
        [
            "Fútbol", "Vóley", "Natación", "Atletismo", "Tenis de mesa",
            "Ciclismo", "Baloncesto", "Karate", "Artes marciales", "Cocina",
            "Videojuegos", "Baile", "Yoga", "Robótica", "Dibujo"
        ]
    )

    # Selección de color favorito
    color = st.color_picker(
        "Color principal de la interfaz",
        "#4CAF50"
    )

    # Botón para iniciar sesión
    if st.button("Iniciar sesión pedagógica"):
        # Guardamos los datos en la sesión
        st.session_state.alumno_id = alumno_id
        st.session_state.edad = edad
        st.session_state.actividad = actividad
        st.session_state.color = color
        st.session_state.sesion_iniciada = True

        # Inicializamos el primer tema y nivel desde TEMAS
        primer_tema = list(TEMAS.keys())[0]
        primer_nivel = "basico"
        st.session_state.tema_actual = primer_tema
        st.session_state.nivel_actual = primer_nivel

        st.rerun()  # Reinicia la app para cargar la pantalla principal

# -------------------------------------------------
# Pantalla principal después del inicio de sesión
# -------------------------------------------------
else:
    # Aplicar color elegido por el alumno a toda la interfaz
    st.markdown(
        f"""
        <style>
        .stApp {{
            background-color: {st.session_state.color}20;  /* El 20 al final aplica transparencia */
        }}
        </style>
        """,
        unsafe_allow_html=True
    )

    st.title("🧠 Ejercicio de Algoritmos")

    # Mostrar información del alumno
    st.info(
        f"Alumno ID: {st.session_state.alumno_id} | "
        f"Edad: {st.session_state.edad} | "
        f"Actividad: {st.session_state.actividad}"
    )

    # Mostrar tema y nivel inicial asignado
    st.write(f"**Tema actual:** {st.session_state.tema_actual}")
    st.write(f"**Nivel actual:** {st.session_state.nivel_actual}")



    ##### CELDA 3: GENERACIÓN DEL PRIMER EJERCICIO DESDE EL BACKEND #######

    # -------------------------------------------------
    # Inicialización del ejercicio actual en sesión
    # -------------------------------------------------
    if "ejercicio_id_actual" not in st.session_state:
        st.session_state.ejercicio_id_actual = None
    
    if "enunciado_actual" not in st.session_state:
        st.session_state.enunciado_actual = None
    
    # -------------------------------------------------
    # Generar primer ejercicio solo si no existe aún
    # -------------------------------------------------
    if st.session_state.ejercicio_id_actual is None:
    
        with st.spinner("Generando ejercicio adaptativo..."):
    
            resultado = orquestador_manager(
                alumno_id=st.session_state.alumno_id,
                tema=st.session_state.tema_actual,
                edad=st.session_state.edad,
                actividad=st.session_state.actividad
            )
    
            st.session_state.ejercicio_id_actual = resultado["ejercicio_id"]
            st.session_state.enunciado_actual = resultado["enunciado"]
    
    # -------------------------------------------------
    # Mostrar ejercicio actual
    # -------------------------------------------------
    if st.session_state.enunciado_actual:
    
        st.subheader("📘 Enunciado del ejercicio")
        st.write(st.session_state.enunciado_actual) 


