# -*- coding: utf-8 -*-
"""V8_backend_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXldPSea7i8S8kKuIdg_QUBaTgY8tCbe
"""

# ================================
# CELDA 1: INSTALACIÓN DE LIBRERÍAS
# ================================

# Instala el núcleo moderno de LangChain (prompts, mensajes, tools, runnables)
# !pip install -q langchain-core    ## esto solo funciona en colab

# Instala la integración oficial con modelos OpenAI (GPT)
#!pip install -q langchain-openai

# Instala componentes comunitarios (conectores, utilidades opcionales)
#!pip install -q langchain-community

# Instala LangGraph (base moderna para agentes; NO usaremos create_react_agent deprecated)
#!pip install -q langgraph

# Driver PostgreSQL para Python (conexión directa a Postgres)
#!pip install -q psycopg2-binary

# Para exponer el backend en Colab
#!pip install -q fastapi uvicorn nest_asyncio pyngrok

# =========================================
# CELDA 2: CONFIGURACIÓN DE LA API DE OPENAI
# =========================================

# Importa la librería estándar de Python para manejar variables de entorno
# Abre el archivo de texto donde guardaste tu API Key
# IMPORTANTE: el archivo solo contiene la clave, nada más
import os
api_key = os.getenv("OPENAI_API_KEY")

# Importaciones principales (MODERNAS, NO DEPRECADAS)
# Modelo de lenguaje GPT a usar
from langchain_openai import ChatOpenAI

# Plantillas de prompts estructurados
from langchain_core.prompts import ChatPromptTemplate

# Mensajes del sistema, usuario y contexto
from langchain_core.messages import HumanMessage, SystemMessage

# Utilidad para definir herramientas personalizadas
from langchain_core.tools import tool

# =========================================
# CELDA 3: INICIALIZACIÓN DEL MODELO LLM
# =========================================

# Inicializa el modelo GPT
# gpt-3.5-turbo es estable, barato y suficiente para la VERSIÓN 1
objeto_llm = ChatOpenAI(
    model="gpt-3.5-turbo",
    temperature=0.7   # Controla creatividad (0 = rígido, 1 = más creativo)
)

# =========================================
# CELDA 4: HERRAMIENTA generar_ejercicio EN PSEUDOCÓDIGO - Es un generador de prompt
# =========================================

from langchain_core.tools import tool

# ---------------------------------------------------------
# Herramienta que genera enunciados en pseudocódigo
# SOLO usa variables relevantes para el LLM
# ---------------------------------------------------------
@tool
def generador_prompt_ejercicio(
    edad: int,
    nivel: str,
    actividad: str,
    tema: str
) -> str:
    """
    Genera un ejercicio en pseudocódigo (NO código en un lenguaje real).
    El ejercicio debe ser:
    - Adecuado a la edad del estudiante
    - Ajustado al nivel académico que puede ser basico, intermedio o avanzado
    - Contextualizado a su actividad favorita
    - Enfocado únicamente en el tema indicado
    No incluye la solución.
    """

    return (
        f"Genera un ejercicio en pseudocódigo sobre {tema}, "
        f"nivel {nivel}, para un alumno de {edad} años "
        f"al que le gusta la {actividad}. "
        f"No resuelvas el ejercicio."
    )

"""En la celda 4, simularemos unos datos de entrada y veremos la salida
Entrada
prompt = generador_prompt_ejercicio(
    edad=16,
    nivel="básico",
    actividad="Natación",
    tema="Bucles"
)

Salida (texto plano)
"Genera un ejercicio en pseudocódigo sobre Bucles, nivel básico, para un alumno de 16 años al que le gusta la Natación. No resuelvas el ejercicio."

"""

# =========================================
# CELDA 5: CREACIÓN DEL AGENTE EDUCATIVO
# =========================================

from langchain.agents import create_agent

# Prompt del sistema (rol del agente)
prompt_sistema = """
Eres un agente educativo.
Generas únicamente enunciados de ejercicios en PSEUDOCÓDIGO.
No resuelves los ejercicios.
Debes usar la herramienta generador_prompt_ejercicio.
"""

# Creación del agente y enlace con la herramienta creada llamada generador_prompt_ejercicio
agent = create_agent(
    model=objeto_llm,
    tools=[generador_prompt_ejercicio],
    system_prompt=prompt_sistema
)

# =========================================
# CELDA 6: FUNCIÓN ORQUESTADORA DEL FLUJO PEDAGÓGICO COMPLETO
# =========================================
# La funcion orquestador_ejercicio no hace nada en su interior, pero permite acceder a los parametros del flujo de datos como historial edad, coloer, etc
# La funcion orquestador_ejercicio no es solo una función cualquiera: es como el director de orquesta que organiza toda la información del alumno, decide
# ajustes pedagógicos según el historial y prepara el mensaje que va a “hablarle” al LLM. Sin esta función, todos esos datos y reglas quedarían desordenados
# y el agente no podría trabajar de forma coherente.
#
# - La función centraliza y gestiona los datos del alumno. Aqui solo existe una funcion que retorna un str, el cual es:  return resultado["messages"][-1].content
# - Controla la adaptación pedagógica (sube, baja o mantiene nivel según desempeño).
# - Construye el prompt para el LLM.
# - Devuelve finalmente el enunciado del ejercicio listo para mostrar al alumno.



def orquestador_ejercicio( edad: int, nivel: str, actividad: str, tema: str, color: str = None, historial: dict = None, solicitar_ayuda: bool = False) -> str:
    """
    Orquesta la generación de un ejercicio en pseudocódigo con flujo pedagógico.

    Parámetros:
    - edad: edad del alumno
    - nivel: 'básico', 'intermedio' o 'avanzado'
    - actividad: actividad favorita del alumno
    - tema: tema de estudio
    - color: color favorito del alumno (opcional, para interfaz)
    - historial: diccionario con desempeño previo del alumno (opcional)
    - solicitar_ayuda: si el alumno pide ayuda (opcional)

    Retorna:
    - Enunciado del ejercicio generado por el agente
    """

    # ---------------------------------------------------------
    # 1️⃣ Ajuste pedagógico del nivel
    # ---------------------------------------------------------
    if historial:
        # Si el alumno ha resuelto correctamente los últimos ejercicios
        exitos = historial.get("ejercicios_correctos", 0)
        fallos = historial.get("ejercicios_fallidos", 0)

        if exitos >= 3 and nivel == "básico":
            nivel = "intermedio"
        elif exitos >= 3 and nivel == "intermedio":
            nivel = "avanzado"
        elif fallos >= 2 and nivel == "intermedio":
            nivel = "básico"
        # Avanzado se mantiene como máximo

    # ---------------------------------------------------------
    # 2️⃣ Construir prompt para el agente
    # ---------------------------------------------------------
    mensaje_usuario = (
        f"Genera un ejercicio en pseudocódigo para un alumno de {edad} años, "
        f"nivel {nivel}, le gusta la {actividad}, sobre {tema}."
    )

    if color:
        mensaje_usuario += f" Su color favorito es {color}."

    if solicitar_ayuda:
        mensaje_usuario += " Incluye pistas o sugerencias para ayudar al alumno."

    entrada_agente = {
        "messages": [
            {"role": "user", "content": mensaje_usuario}
        ]
    }

    # ---------------------------------------------------------
    # 3️⃣ Invocar el agente moderno
    # ---------------------------------------------------------
    resultado = agent.invoke(entrada_agente)

    # ---------------------------------------------------------
    # 4️⃣ Devolver solo el enunciado generado
    # ---------------------------------------------------------
    return resultado["messages"][-1].content

# =========================================
# CELDA 7: CONEXIÓN A POSTGRESQL (SUPABASE)
# =========================================

import psycopg2
from psycopg2.extras import RealDictCursor

# ---------------------------------------------------------
# Parámetros de conexión a Supabase
# (usa los datos que ya verificaste que funcionan)
# ---------------------------------------------------------

DB_HOST = "aws-0-us-west-2.pooler.supabase.com"
DB_PORT = 6543
DB_NAME = "postgres"
DB_USER = "postgres.aoduqewpdufjlptdwkpz"
DB_PASSWORD = "Sistemas=2026"  # ← NO uses YOUR-PASSWORD

# ---------------------------------------------------------
# Función para obtener una conexión a la base de datos
# ---------------------------------------------------------
def obtener_conexion():
    """
    Crea y devuelve una conexión activa a PostgreSQL (Supabase).
    Esta función será reutilizada por todo el sistema.
    """
    try:
        conexion = psycopg2.connect(
            host=DB_HOST,
            port=DB_PORT,
            dbname=DB_NAME,
            user=DB_USER,
            password=DB_PASSWORD,
            cursor_factory=RealDictCursor  # resultados como diccionarios
        )
        return conexion
    except Exception as e:
        print("❌ Error al conectar con la base de datos")
        raise e

# Commented out IPython magic to ensure Python compatibility.
# =========================================
# CELDA 8: ACTUALIZACIÓN DEL PROGRESO ACADÉMICO
# =========================================
# Esta celda:
# - Registra métricas agregadas del alumno
# - Actualiza progreso POR TEMA
# - Actualiza progreso GLOBAL (tema = 'GLOBAL')
# - Usa SOLO la función obtener_conexion()
# - Todas las métricas se calculan UNA SOLA VEZ

from datetime import datetime


def actualizar_progreso_academico(
    alumno_id: int,
    tema: str,
    nivel: str,
    fue_correcto: bool,
    tiempo_intento_segundos: int,
    pidio_ayuda: bool = False,
    tipo_ayuda: str | None = None  ):
    """
    Actualiza la tabla progreso_academico con métricas agregadas.

    Se registran:
    - ejercicios_correctos / fallidos
    - total_intentos
    - total_tiempo_segundos
    - total_ayudas
    - último tipo de ayuda
    - promedios por ejercicio

    Se actualiza:
    - una fila por (alumno, tema)
    - una fila GLOBAL por alumno
    """

    # ---------------------------------------------------------
    # 1️⃣ Cálculo ÚNICO de métricas (regla de oro)
    # ---------------------------------------------------------
    ejercicios_correctos = 1 if fue_correcto else 0
    ejercicios_fallidos  = 0 if fue_correcto else 1
    total_intentos       = 1
    total_ayudas         = 1 if pidio_ayuda else 0
    tiempo_total         = tiempo_intento_segundos
    ahora                = datetime.now()

    # ---------------------------------------------------------
    # 2️⃣ Conexión a PostgreSQL (Supabase)
    # ---------------------------------------------------------
    conexion = obtener_conexion()
    cursor = conexion.cursor()

    # ---------------------------------------------------------
    # 3️⃣ Función interna: UPSERT por tema
    # ---------------------------------------------------------
    def guardar_o_actualizar_progreso(tema_actual: str):
        cursor.execute(
            """
            INSERT INTO progreso_academico (
                alumno_id,
                tema,
                nivel,
                ejercicios_correctos,
                ejercicios_fallidos,
                total_intentos,
                total_tiempo_segundos,
                total_ayudas,
                ultimo_tipo_ayuda,
                promedio_intentos_por_ejercicio,
                promedio_tiempo_por_ejercicio,
                ultima_actualizacion
            )
            VALUES (
#                 %s,
#                 %s,
#                 %s,
#                 %s,
#                 %s,
#                 %s,
#                 %s,
#                 %s,
#                 %s,
#                 %s,
#                 %s,
#                 %s
            )
            ON CONFLICT (alumno_id, tema)
            DO UPDATE SET
                ejercicios_correctos = progreso_academico.ejercicios_correctos + %s,
                ejercicios_fallidos  = progreso_academico.ejercicios_fallidos  + %s,
                total_intentos       = progreso_academico.total_intentos + %s,
                total_tiempo_segundos= progreso_academico.total_tiempo_segundos + %s,
                total_ayudas         = progreso_academico.total_ayudas + %s,
                ultimo_tipo_ayuda    = %s,
                promedio_intentos_por_ejercicio =
                    (progreso_academico.total_intentos + %s)::FLOAT /
                    NULLIF(
                        progreso_academico.ejercicios_correctos +
                        progreso_academico.ejercicios_fallidos +
#                         %s + %s, 0
                    ),
                promedio_tiempo_por_ejercicio =
                    (progreso_academico.total_tiempo_segundos + %s)::FLOAT /
                    NULLIF(
                        progreso_academico.ejercicios_correctos +
                        progreso_academico.ejercicios_fallidos +
#                         %s + %s, 0
                    ),
                ultima_actualizacion = %s
            """,
            (
                # INSERT
                alumno_id,
                tema_actual,
                nivel,
                ejercicios_correctos,
                ejercicios_fallidos,
                total_intentos,
                tiempo_total,
                total_ayudas,
                tipo_ayuda,
                float(total_intentos),
                float(tiempo_total),
                ahora,

                # UPDATE
                ejercicios_correctos,
                ejercicios_fallidos,
                total_intentos,
                tiempo_total,
                total_ayudas,
                tipo_ayuda,

                total_intentos,
                ejercicios_correctos,
                ejercicios_fallidos,

                tiempo_total,
                ejercicios_correctos,
                ejercicios_fallidos,

                ahora
            )
        )

    # ---------------------------------------------------------
    # 4️⃣ Actualizar progreso por TEMA
    # ---------------------------------------------------------
    guardar_o_actualizar_progreso(tema)

    # ---------------------------------------------------------
    # 5️⃣ Actualizar progreso GLOBAL del alumno
    # ---------------------------------------------------------
    guardar_o_actualizar_progreso("GLOBAL")

    # ---------------------------------------------------------
    # 6️⃣ Commit y cierre
    # ---------------------------------------------------------
    conexion.commit()
    cursor.close()
    conexion.close()

# =========================================
# CELDA 9: REGISTRO DE INTENTOS DE EJERCICIOS
# (VERSIÓN NORMALIZADA Y DOCUMENTADA)
# =========================================

from datetime import datetime


def registrar_intento_ejercicio(
    alumno_id: int,
    ejercicio_id: int,
    intento_numero: int,
    fue_correcto: bool,
    tiempo_intento_segundos: int,
    pidio_ayuda: bool = False,
    tipo_ayuda: str | None = None
):
    """
    Registra UN intento del alumno sobre UN ejercicio específico.

    🔹 Diseño normalizado:
    - No se guarda el enunciado
    - No se repite tema ni nivel
    - Todo eso vive en la tabla ejercicios

    Esta tabla representa eventos atómicos (micro-nivel).
    """

    # ---------------------------------------------------------
    # 1️⃣ Timestamps del intento
    # ---------------------------------------------------------
    # Por ahora inicio y fin son el mismo instante.
    # Si luego mides tiempo real desde frontend,
    # aquí SOLO se ajusta esta parte.
    inicio_intento = datetime.now()
    fin_intento = inicio_intento

    # ---------------------------------------------------------
    # 2️⃣ Conexión a PostgreSQL (Supabase)
    # ---------------------------------------------------------
    conexion = obtener_conexion()
    cursor = conexion.cursor()

    # ---------------------------------------------------------
    # 3️⃣ Inserción del evento de intento
    # ---------------------------------------------------------
    # NOTA CLAVE:
    # - ejercicio_id es la FK que conecta con el enunciado
    # - esta tabla NO calcula métricas
    # - SOLO registra hechos
    cursor.execute(
        """
        INSERT INTO historial_ejercicios (
            alumno_id,
            ejercicio_id,
            intento_numero,
            fue_correcto,
            tiempo_intento_segundos,
            pidio_ayuda,
            tipo_ayuda,
            inicio_intento,
            fin_intento
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
        (
            alumno_id,
            ejercicio_id,
            intento_numero,
            fue_correcto,
            tiempo_intento_segundos,
            pidio_ayuda,
            tipo_ayuda,
            inicio_intento,
            fin_intento
        )
    )

    # ---------------------------------------------------------
    # 4️⃣ Commit y cierre
    # ---------------------------------------------------------
    conexion.commit()
    cursor.close()
    conexion.close()

# =========================================
# CELDA 10:
# =========================================
# Objetivo: A partir del estado en progreso_academico, decidir qué hacer con el alumno:
# subir nivel
# bajar nivel
# mantener nivel
# recomendar refuerzo
# recomendar avanzar


def decidir_siguiente_paso(alumno_id: int, tema: str):
    """
    -------------------------------------------
    Decide el siguiente paso pedagógico del alumno
    usando la tabla progreso_academico.

    SMP:
    - Sense: lee el estado actual
    - Model: interpreta desempeño
    - Plan: decide acción pedagógica
    """

    conexion = obtener_conexion()
    cursor = conexion.cursor()

    query = """
        SELECT
            nivel,
            ejercicios_correctos,
            ejercicios_fallidos,
            total_intentos,
            total_tiempo_segundos,
            total_ayudas,
            promedio_intentos_por_ejercicio,
            promedio_tiempo_por_ejercicio
        FROM progreso_academico
        WHERE alumno_id = %s
          AND tema = %s
        LIMIT 1;
    """

    cursor.execute(query, (alumno_id, tema))
    registro = cursor.fetchone()

    cursor.close()
    conexion.close()

    # Si no hay datos aún
    if registro is None:
        return {
            "accion": "iniciar",
            "mensaje": "Alumno inicia en nivel básico",
            "nivel_sugerido": "básico"
        }

    # -----------------------------
    # MODELO (interpretación)
    # -----------------------------
    correctos = registro["ejercicios_correctos"]
    fallidos = registro["ejercicios_fallidos"]
    intentos = registro["total_intentos"]
    ayudas = registro["total_ayudas"]
    nivel_actual = registro["nivel"]

    if intentos == 0:
        tasa_exito = 0
    else:
        tasa_exito = correctos / intentos

    # -----------------------------
    # PLAN (reglas pedagógicas)
    # -----------------------------

    # Caso 1: desempeño alto → subir nivel
    if tasa_exito >= 0.8 and ayudas == 0:
        return {
            "accion": "avanzar",
            "mensaje": "Alto desempeño, puede subir de nivel",
            "nivel_actual": nivel_actual,
            "nivel_sugerido": "intermedio" if nivel_actual == "básico" else "avanzado"
        }

    # Caso 2: muchos fallos → reforzar
    if fallidos >= correctos:
        return {
            "accion": "reforzar",
            "mensaje": "Se recomienda refuerzo y ejercicios guiados",
            "nivel_actual": nivel_actual,
            "nivel_sugerido": nivel_actual
        }

    # Caso 3: muchas ayudas → mantener nivel
    if ayudas >= intentos * 0.5:
        return {
            "accion": "mantener",
            "mensaje": "Mantener nivel con apoyo gradual",
            "nivel_actual": nivel_actual,
            "nivel_sugerido": nivel_actual
        }

    # Caso 4: progreso normal
    return {
        "accion": "continuar",
        "mensaje": "Continuar con ejercicios del mismo nivel",
        "nivel_actual": nivel_actual,
        "nivel_sugerido": nivel_actual
    }

# =========================================
# CELDA 11: ORQUESTADOR MANAGER
# (VERSIÓN NORMALIZADA Y COHERENTE CON BD)
# =========================================

def orquestador_manager(alumno_id: int, tema: str, edad: int, actividad: str):
    """
    Orquesta el flujo pedagógico COMPLETO para un alumno y un tema.

    Integra:
    - Decisión pedagógica (SMP)
    - Generación del ejercicio (LLM)
    - Persistencia del ejercicio (tabla ejercicios)

    ❗ IMPORTANTE:
    Esta función NO registra intentos.
    SOLO crea el ejercicio.
    """

    # ---------------------------------------------------------
    # 1️⃣ DECISIÓN PEDAGÓGICA (SMP - Sense / Model / Plan)
    # ---------------------------------------------------------
    decision = decidir_siguiente_paso(alumno_id, tema)

    accion = decision["accion"]
    nivel_sugerido = decision["nivel_sugerido"]

    print(f"[INFO] Acción: {accion} | Nivel: {nivel_sugerido}")

    # ---------------------------------------------------------
    # 2️⃣ Si NO corresponde generar ejercicio, se detiene
    # ---------------------------------------------------------
    if accion not in ["iniciar", "avanzar", "continuar"]:
        return {
            "decision": decision,
            "ejercicio_id": None,
            "enunciado": None
        }

    # ---------------------------------------------------------
    # 3️⃣ Generación del ejercicio con el agente educativo
    # ---------------------------------------------------------
    # Aquí SOLO se genera texto.
    # No se guarda aún.
    enunciado = orquestador_ejercicio(
        edad=edad,
        nivel=nivel_sugerido,
        actividad=actividad,
        tema=tema
    )

    # ---------------------------------------------------------
    # 4️⃣ Persistencia del ejercicio (tabla ejercicios)
    # ---------------------------------------------------------
    # Este paso permite:
    # - evitar repetir enunciados
    # - reutilizar el ejercicio
    # - vincular múltiples intentos
    conexion = obtener_conexion()
    cursor = conexion.cursor()

    cursor.execute(
        """
        INSERT INTO ejercicios (
            tema,
            nivel,
            enunciado
        )
        VALUES (%s, %s, %s)
        RETURNING id
        """,
        (tema, nivel_sugerido, enunciado)
    )

    # Se obtiene el ID del ejercicio recién creado
    ejercicio_id = cursor.fetchone()["id"]

    conexion.commit()
    cursor.close()
    conexion.close()

    # ---------------------------------------------------------
    # 5️⃣ Retorno al sistema / frontend
    # ---------------------------------------------------------
    return {
        "decision": decision,
        "ejercicio_id": ejercicio_id,
        "enunciado": enunciado
    }

# =========================================
# CELDA 12: FLUJO COMPLETO DE UN INTENTO
# =========================================
# Esta celda representa el "caso real":
# 1. El sistema ya generó un ejercicio (CELDA 11)
# 2. El alumno intenta resolverlo
# 3. Se registra el intento (micro-nivel)
# 4. Se actualiza el progreso académico (macro-nivel)

def procesar_intento_completo(
    alumno_id: int,
    ejercicio_id: int,
    tema: str,
    nivel: str,
    fue_correcto: bool,
    tiempo_intento_segundos: int,
    pidio_ayuda: bool = False,
    tipo_ayuda: str | None = None,
    intento_numero: int = 1
):
    """
    Procesa un intento REAL de un alumno sobre un ejercicio.

    Esta función:
    - NO genera ejercicios
    - NO decide pedagogía
    - SOLO registra hechos y métricas

    Es clave para:
    - trazabilidad
    - análisis estadístico
    - exportación de datos para la tesis
    """

    # ---------------------------------------------------------
    # 1️⃣ Registrar intento individual (tabla historial_ejercicios)
    # ---------------------------------------------------------
    # Nivel MICRO: cada acción del alumno queda registrada. Llama a laa funcion registrar_intento_ejercicio
    registrar_intento_ejercicio(
        alumno_id=alumno_id,
        ejercicio_id=ejercicio_id,
        intento_numero=intento_numero,
        fue_correcto=fue_correcto,
        tiempo_intento_segundos=tiempo_intento_segundos,
        pidio_ayuda=pidio_ayuda,
        tipo_ayuda=tipo_ayuda
    )

    # ---------------------------------------------------------
    # 2️⃣ Actualizar progreso académico agregado
    # ---------------------------------------------------------
    # Nivel MACRO: métricas acumuladas por tema y global. LLama a la funcion actualizar_progreso_academico
    actualizar_progreso_academico(
        alumno_id=alumno_id,
        tema=tema,
        nivel=nivel,
        fue_correcto=fue_correcto,
        tiempo_intento_segundos=tiempo_intento_segundos,
        pidio_ayuda=pidio_ayuda,
        tipo_ayuda=tipo_ayuda
    )

    # ---------------------------------------------------------
    # 3️⃣ Retorno de confirmación (útil para frontend / logs)
    # ---------------------------------------------------------
    return {
        "status": "ok",
        "alumno_id": alumno_id,
        "ejercicio_id": ejercicio_id,
        "intento_numero": intento_numero,
        "fue_correcto": fue_correcto,
        "tiempo": tiempo_intento_segundos,
        "pidio_ayuda": pidio_ayuda
    }

# =========================================
# CELDA 13: CIERRE DE APRENDIZAJE
# =========================================
# Esta celda:
# - Cierra un intento del alumno
# - Consulta el ejercicio REAL desde la BD
# - Registra el intento (micro)
# - Actualiza el progreso académico (macro)
# =========================================

from datetime import datetime

def cerrar_intento_aprendizaje(
    alumno_id: int,
    ejercicio_id: int,
    intento_numero: int,
    fue_correcto: bool,
    tiempo_intento_segundos: int,
    pidio_ayuda: bool = False,
    tipo_ayuda: str | None = None
):
    """
    Cierra un intento de aprendizaje del alumno.

    Flujo:
    1. Obtiene datos del ejercicio (tema, nivel)
    2. Registra intento en historial_ejercicios
    3. Actualiza progreso_academico
    """

    conexion = obtener_conexion()
    cursor = conexion.cursor()

    # -------------------------------------------------
    # 1️⃣ Obtener datos del ejercicio (FUENTE DE VERDAD)
    # -------------------------------------------------
    cursor.execute(
        """
        SELECT id, tema, nivel
        FROM ejercicios
        WHERE id = %s
        LIMIT 1
        """,
        (ejercicio_id,)
    )

    ejercicio = cursor.fetchone()

    if ejercicio is None:
        cursor.close()
        conexion.close()
        raise ValueError(f"Ejercicio con ID {ejercicio_id} no existe")

    tema = ejercicio["tema"]
    nivel = ejercicio["nivel"]

    # -------------------------------------------------
    # 2️⃣ Registrar intento (MICRO NIVEL)
    # -------------------------------------------------
    fin_intento = datetime.now()
    inicio_intento = fin_intento  # simplificado

    cursor.execute(
        """
        INSERT INTO historial_ejercicios (
            alumno_id,
            ejercicio_id,
            intento_numero,
            fue_correcto,
            tiempo_intento_segundos,
            pidio_ayuda,
            tipo_ayuda,
            inicio_intento,
            fin_intento
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
        (
            alumno_id,
            ejercicio_id,
            intento_numero,
            fue_correcto,
            tiempo_intento_segundos,
            pidio_ayuda,
            tipo_ayuda,
            inicio_intento,
            fin_intento
        )
    )

    # -------------------------------------------------
    # 3️⃣ Actualizar progreso académico (MACRO NIVEL)
    # -------------------------------------------------
    actualizar_progreso_academico(
        alumno_id=alumno_id,
        tema=tema,
        nivel=nivel,
        fue_correcto=fue_correcto,
        tiempo_intento_segundos=tiempo_intento_segundos,
        pidio_ayuda=pidio_ayuda,
        tipo_ayuda=tipo_ayuda
    )

    conexion.commit()
    cursor.close()
    conexion.close()

    return {
        "estado": "ok",
        "alumno_id": alumno_id,
        "ejercicio_id": ejercicio_id,
        "tema": tema,
        "nivel": nivel,
        "fue_correcto": fue_correcto
    }

# ==============================
# CELDA 14 – ORQUESTADOR PEDAGÓGICO COMPLETO (VERSIÓN DEPURABLE)
# ==============================
# Objetivo:
# - Integrar cierre de intento (CELDA 13)
# - Decisión pedagógica SMP (CELDA 10)
# - Generación de nuevo ejercicio adaptativo (CELDA 6)
# - Retornar decisión pedagógica + ejercicio generado + flags de ayuda
# - Esta celda representa el AGENTE PEDAGÓGICO completo

def orquestador_pedagogico(
    alumno_id: int,
    ejercicio_id: int,
    intento_numero: int,
    fue_correcto: bool,
    tiempo_intento_segundos: int,
    edad: int,
    actividad: str,
    pidio_ayuda: bool = False,
    tipo_ayuda: str | None = None
):
    """
    Orquesta todo el flujo pedagógico de un alumno.

    Flujo:
    1️⃣ Cierra intento anterior y actualiza progreso (CELDA 13)
    2️⃣ Evalúa desempeño y decide acción pedagógica (SMP - CELDA 10)
    3️⃣ Genera nuevo ejercicio si corresponde (CELDA 6)
    4️⃣ Persiste el ejercicio en la BD
    """

    # 1️⃣ Cierre del intento actual (MICRO + MACRO)
    cierre = cerrar_intento_aprendizaje(
        alumno_id=alumno_id,
        ejercicio_id=ejercicio_id,
        intento_numero=intento_numero,
        fue_correcto=fue_correcto,
        tiempo_intento_segundos=tiempo_intento_segundos,
        pidio_ayuda=pidio_ayuda,
        tipo_ayuda=tipo_ayuda
    )

    # 2️⃣ Leer tema y nivel del ejercicio cerrado
    tema = cierre["tema"]
    nivel_actual = cierre["nivel"]

    # 3️⃣ Decidir siguiente paso pedagógico (SMP)
    decision = decidir_siguiente_paso(alumno_id, tema)
    accion = decision.get("accion", None)
    nivel_sugerido = decision.get("nivel_sugerido", nivel_actual)

    # 4️⃣ Inicializar variables de resultado
    nuevo_ejercicio_id = None
    enunciado = None
    ayuda_incluida = False

    # 5️⃣ Generar nuevo ejercicio SOLO si la acción lo requiere
    if accion in ["iniciar", "avanzar", "continuar"]:
        # Determinar si incluir ayuda según reglas
        incluir_ayuda = False
        if accion == "iniciar":
            incluir_ayuda = True   # alumno nuevo siempre recibe guía
        elif pidio_ayuda or decision.get("accion") == "reforzar":
            incluir_ayuda = True

        ayuda_incluida = incluir_ayuda

        # Llamada al agente educativo (CELDA 6)
        enunciado = orquestador_ejercicio(
            edad=edad,
            nivel=nivel_sugerido,
            actividad=actividad,
            tema=tema,
            solicitar_ayuda=incluir_ayuda
        )

        # Persistencia del ejercicio (tabla ejercicios)
        conexion = obtener_conexion()
        cursor = conexion.cursor()
        cursor.execute(
            """
            INSERT INTO ejercicios (tema, nivel, enunciado)
            VALUES (%s, %s, %s)
            RETURNING id
            """,
            (tema, nivel_sugerido, enunciado)
        )
        nuevo_ejercicio_id = cursor.fetchone()["id"]
        conexion.commit()
        cursor.close()
        conexion.close()

    # 6️⃣ Retornar estructura completa del flujo pedagógico
    return {
        "cierre_intento": cierre,              # resultado de CELDA 13
        "decision_pedagogica": decision,      # resultado de CELDA 10
        "nuevo_ejercicio_id": nuevo_ejercicio_id,
        "enunciado": enunciado,
        "ayuda_incluida": ayuda_incluida
    }
